# PCBWay Fabrication Files
# Reference: https://www.pcbway.com/blog/PCB_Design_Tutorial/How_to_Export_Gerber_and_Production_Files_in_KiCad.html
# Reference: https://github.com/INTI-CMNB/KiBot/blob/ff2c6ff9bd64d3941268876bdf301001cc8290bd/kibot/resources/config_templates/PCBWay.kibot.yaml

kibot:
  version: 1

outputs:
  - name: pcbway_gbr
    comment: Gerbers compatible with PCBWay
    type: gerber
    dir: fabrication/pcbway/gerbers
    options: &gerber_options
      exclude_edge_layer: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      subtract_mask_from_silk: true # Ensure no silkscreen on pads
      output: "%f.%x"
    layers:
      - F.Cu
      - B.Cu
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: pcbway_drl
    comment: Drill files compatible with PCBWay
    type: excellon
    dir: fabrication/pcbway/gerbers
    options:
      pth_and_npth_single_file: false
      metric_units: false
      route_mode_for_oval_holes: true
      pth_id: ''
      npth_id: '-NPTH'
      output: "%f%i.drl"

  - name: pcbway_zip
    comment: ZIP file for pcbway
    type: compress
    dir: fabrication/pcbway
    options:
      move_files: true
      output: "%f_gerber_pcbway.%x"
      files:
        - from_output: pcbway_gbr
          dest: /
        - from_output: pcbway_drl
          dest: /
